package com.example.questnavigasitugas_020


data class Peserta(
    val id: Int,
    val nama: String,
    val gender: String,
    val status: String,
    val alamat: String
)

val dummyPesertaList = listOf(
    Peserta(1,
        "Muhammad Wildan Indi Naufal",
        "Laki-laki",
        "Lajang",
        "Bantul"),
    Peserta(2,
        "Bunga Annisa Putri Handani",
        "Perempuan",
        "Lajang",
        "Bantul"),
    Peserta(3, "Bagas Dwi Surahman",
        "Laki-laki",
        "Lajang",
        "Jogja"),
    Peserta(4, "Dewi Lestari",
        "Perempuan",
        "Kawin",
        "Sleman"),
    Peserta(5, "Budi Santoso",
        "Laki-laki",
        "Lajang",
        "Gunung Kidul"),
    Peserta(6, "Dean Dwi Bekti",
        "Perempuan",
        "Lajang",
        "Jogja"),
    Peserta(7, "Eko Prasetyo",
        "Laki-laki",
        "Kawin",
        "Bantul"),
    Peserta(8, "Fitria Handayani",
        "Perempuan",
        "Cerai",
        "Kulon Progo"),
    Peserta(9, "Gunawan Wibisono",
        "Laki-laki",
        "Lajang",
        "Sleman"),
    Peserta(10, "Indah Permata",
        "Perempuan",
        "Kawin",
        "Jogja")
)